### ISSUE TITLE
compiled failed with windows system.

### ISSUE THREAD

**Issue by AlecHang** [juhyeonkim95/Mitsuba3DopplerToF#12]
I compiled successfully with the orignal mitsuba 3, but failed in this repo. Can anyone give me a hand?

  OS: windows 11
  CPU: 
  GPU: rtx 3070
  Python version: Python 3.11.5
  CUDA version:  12.2
  NVidia driver: 536.99

Dr.Jit v0.4.2

**Here is the error:**
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(5823,13): error C2666: “mitsuba::ref<mitsuba::ShapeGroup<drjit::DiffArray<drjit::CUDAArray<float>>,mitsuba::Color<drjit::DiffArray<drjit::CUDAArray<float>>,3>>>::operator ==”: 重载函数具有类似的转换 [C:\Users\Admin\projects\Mitsuba3DopplerToF\build\src\render\mitsuba-render.vcxproj]

It seens that nn overloading error occurred when compiling "../../../src/render/scene.cpp”.

**Below is the whole output from the cmd:**

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(5823,13): error C266
6: “mitsuba::ref<mitsuba::ShapeGroup<drjit::DiffArray<drjit::LLVMArray<float>>,mitsuba::Color<drjit::DiffArray<drjit::L
LVMArray<float>>,3>>>::operator ==”: 重载函数具有类似的转换 [C:\Users\Admin\projects\Mitsuba3DopplerToF\build\src\render\mitsuba-r
ender.vcxproj]
  (编译源文件“../../../src/render/scene.cpp”)
  C:\Users\Admin\projects\Mitsuba3DopplerToF\include\mitsuba\core\object.h(230,10):
  可能是“bool mitsuba::ref<mitsuba::ShapeGroup<drjit::DiffArray<drjit::LLVMArray<float>>,mitsuba::Color<drjit::DiffArray<d
  rjit::LLVMArray<float>>,3>>>::operator ==(const T *) const”
          with
          [
              T=mitsuba::ShapeGroup<drjit::DiffArray<drjit::LLVMArray<float>>,mitsuba::Color<drjit::DiffArray<drjit::LL
  VMArray<float>>,3>>
          ]
  C:\Users\Admin\projects\Mitsuba3DopplerToF\include\mitsuba\core\object.h(224,10):
  或    “bool mitsuba::ref<mitsuba::ShapeGroup<drjit::DiffArray<drjit::LLVMArray<float>>,mitsuba::Color<drjit::DiffArray
  <drjit::LLVMArray<float>>,3>>>::operator ==(const mitsuba::ref<mitsuba::ShapeGroup<drjit::DiffArray<drjit::LLVMArray<
  float>>,mitsuba::Color<drjit::DiffArray<drjit::LLVMArray<float>>,3>>> &) const”
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(5823,13):
  或       “内置 C++ operator==(T，T)"
          with
          [
              T=mitsuba::ShapeGroup<drjit::DiffArray<drjit::LLVMArray<float>>,mitsuba::Color<drjit::DiffArray<drjit::LL
  VMArray<float>>,3>>
          ]
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(5823,13):
  或       “内置 C++ operator==(T，T)"
          with
          [
              T=mitsuba::ShapeGroup<drjit::DiffArray<drjit::LLVMArray<float>>,mitsuba::Color<drjit::DiffArray<drjit::LL
  VMArray<float>>,3>>
          ]
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(5823,13):
  尝试匹配参数列表“(mitsuba::ref<mitsuba::ShapeGroup<drjit::DiffArray<drjit::LLVMArray<float>>,mitsuba::Color<drjit::DiffArray<
  drjit::LLVMArray<float>>,3>>>, const _Ty)”时
          with
          [
              _Ty=mitsuba::ShapeGroup<drjit::DiffArray<drjit::LLVMArray<float>>,mitsuba::Color<drjit::DiffArray<drjit::
  LLVMArray<float>>,3>> *
          ]
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(5823,13):
  注意: 限定调整(const/volatile)可能会造成多义性
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(5823,13):
  模板实例化上下文(最早的实例化上下文)为
        C:\Users\Admin\projects\Mitsuba3DopplerToF\include\mitsuba\render\scene.h(597,1):
        查看对正在编译的 类 模板 实例化“mitsuba::Scene<drjit::DiffArray<drjit::LLVMArray<float>>,mitsuba::Color<drjit::DiffArray<drji
  t::LLVMArray<float>>,3>>”的引用
        C:\Users\Admin\projects\Mitsuba3DopplerToF\src\render\scene.cpp(22,67):
        在编译 类 模板 成员函数“mitsuba::Scene<drjit::DiffArray<drjit::LLVMArray<float>>,mitsuba::Color<drjit::DiffArray<drjit::L
  LVMArray<float>>,3>>::Scene(const mitsuba::Properties &)”时
        C:\Users\Admin\projects\Mitsuba3DopplerToF\src\render\scene.cpp(69,21):
        查看对正在编译的函数 模板 实例化“_InIt std::find<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,mitsuba::Sha
  peGroup<drjit::DiffArray<drjit::LLVMArray<float>>,mitsuba::Color<drjit::DiffArray<drjit::LLVMArray<float>>,3>>*>(_InI
  t,const _InIt,mitsuba::ShapeGroup<drjit::DiffArray<drjit::LLVMArray<float>>,mitsuba::Color<drjit::DiffArray<drjit::LL
  VMArray<float>>,3>> *const &)”的引用
          with
          [
              _InIt=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<mitsuba::ref<mitsuba::ShapeGroup<drjit::D
  iffArray<drjit::LLVMArray<float>>,mitsuba::Color<drjit::DiffArray<drjit::LLVMArray<float>>,3>>>>>>,
              _Ty=mitsuba::ref<mitsuba::ShapeGroup<drjit::DiffArray<drjit::LLVMArray<float>>,mitsuba::Color<drjit::Diff
  Array<drjit::LLVMArray<float>>,3>>>
          ]
        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(5837,36):
        查看对正在编译的函数 模板 实例化“_InIt std::_Find_unchecked<mitsuba::ref<mitsuba::ShapeGroup<drjit::DiffArray<drjit::LLVMArray
  <float>>,mitsuba::Color<drjit::DiffArray<drjit::LLVMArray<float>>,3>>>*,_Ty>(_InIt,const _InIt,const _Ty &)”的引用
          with
          [
              _InIt=mitsuba::ref<mitsuba::ShapeGroup<drjit::DiffArray<drjit::LLVMArray<float>>,mitsuba::Color<drjit::Di
  ffArray<drjit::LLVMArray<float>>,3>>> *,
              _Ty=mitsuba::ShapeGroup<drjit::DiffArray<drjit::LLVMArray<float>>,mitsuba::Color<drjit::DiffArray<drjit::
  LLVMArray<float>>,3>> *
          ]

**Comment by AlecHang** [comment]
Solved by commenting out codes in src\render\scene.cpp, from line 67 to line 74.

**Comment by juhyeonkim95** [comment]
Hi,

Changing 
`std::find(m_shapegroups.begin(), m_shapegroups.end(), (ShapeGroup*) shape->get_shapegroup()).` 
to
`std::find(m_shapegroups.begin(), m_shapegroups.end(), shape->get_shapegroup()).`

resolved the problem. I checked it works on Windows.

**Comment by AlecHang** [comment]
It works! thanks a lot!
