### ISSUE TITLE
The compilation was successful, but an error occurred during runtime.

### ISSUE THREAD

**Issue by rslika** [juhyeonkim95/Mitsuba3DopplerToF#13]
## System configuration

System information:

  OS: windows 11
  CPU: amd 7735H
  GPU: nvidia 4060

## Description

I followed the steps in the Mitsuba 3 documentation for compilation, and the compilation was successful, but an error occurred during runtime.The main error message are:

```
Critical Dr.Jit compiler failure: jit_optix_compile(): optixModuleGetCompilationState() indicates that the compilation did not complete succesfully. The module's compilation state is: 0x2363
Please see the PTX assembly listing and error message below:

COMPILE ERROR: Invalid PTX input: ptx2llvm-module-001: error: Failed to parse input PTX string
ptx2llvm-module-001, line 2; fatal   : Unsupported .target 'sm_87'
Cannot parse input PTX string
```
It seems to be a compliation error, however I didn't find any error message in cmake log.

Any solutions provided for this issue would be very helpful, or could anyone please provide a working compilation environment? I will report new compilation results under different environments.

**Comment by juhyeonkim95** [comment]
Hi, What is your cuda + gpu driver version? 

I tested the code works well on both of Ubuntu + 3090 and Windows11 + 4090.

**Comment by rslika** [comment]
It's CUDA v12.3 and driver 546.12 on my device.

**Comment by juhyeonkim95** [comment]
According to the following link, this is a driver issue.

https://github.com/mitsuba-renderer/mitsuba3/issues/803

According to the linke, you can resolve this by (1) downgrade gpu driver (2) or update drjit to the latest version.

It is resolved in current Mitsuba version, but I used previous version for this repo, so it happened.

**Comment by rslika** [comment]
Thanks a lot. I recompiled using Dr.Jit v0.4.6 and successfully ran the tests.
